AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Account Seed to be deployed in each region

Conditions:
  IsMainRegion: !Equals [!Ref AWS::Region, 'us-east-1']

Resources:
  # ----------
  # IAM ROLES
  # ----------
  CodePipelineExecutionRole:
    Condition: IsMainRegion
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipeline-Execution-Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  CloudFormationDeploymentRole:
    Condition: IsMainRegion
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormation-Deployment-Role
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service:
              - cloudformation.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ----------
  # CODEPIPELINE - DevOps-CloudFormation
  # ----------
  DevOpsCloudFormationCodePipelineArtifactsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'devops-cloudformation-codepipeline-artifacts-${AWS::Region}'

  # Create CodePipeline with 2 stages (Source, Build)
  DevOpsCloudFormationCodePipeline:
    Condition: IsMainRegion
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DevOps-Cloudformation-CodePipeline
      ArtifactStores:
        - ArtifactStore:
            Type: S3
            Location: !Ref DevOpsCloudFormationCodePipelineArtifactsS3Bucket
          Region: !Ref AWS::Region
        - ArtifactStore:
            Type: S3
            Location: devops-cloudformation-codepipeline-artifacts-eu-west-1
          Region: 'eu-west-1'
        - ArtifactStore:
            Type: S3
            Location: devops-cloudformation-codepipeline-artifacts-us-west-2
          Region: 'us-west-2'
      RestartExecutionOnUpdate: False
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Version: '1'
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: "arn:aws:codestar-connections:us-east-1:387310632530:connection/c6ff57ad-dab9-4ade-ac7d-ed4a5373c962"
                FullRepositoryId: "Travel-Project-2022/DevOps-Cloudformation"
                BranchName: "master"
                OutputArtifactFormat: "CODE_ZIP"
              RunOrder: 1
              OutputArtifacts:
                - Name: source-output-artifacts
        - Name: Deploy
          Actions:
            - Name: US-East-1-Deployment
              Region: us-east-1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: source-output-artifacts
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudFormationDeploymentRole.Arn
                StackName: DevOps-Cloudformation
                TemplatePath: 'source-output-artifacts::main.cfn.yaml'
              RunOrder: 1
              OutputArtifacts: [ ]
            - Name: EU-West-1-Deployment
              Region: eu-west-1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: source-output-artifacts
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudFormationDeploymentRole.Arn
                StackName: DevOps-Cloudformation
                TemplatePath: 'source-output-artifacts::main.cfn.yaml'
              RunOrder: 1
              OutputArtifacts: [ ]
            - Name: US-West-2-Deployment
              Region: us-west-2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: source-output-artifacts
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudFormationDeploymentRole.Arn
                StackName: DevOps-Cloudformation
                TemplatePath: 'source-output-artifacts::main.cfn.yaml'
              RunOrder: 1
              OutputArtifacts: [ ]

Outputs:
  CodePipelineExecutionRoleArn:
    Condition: IsMainRegion
    Value: !GetAtt CodePipelineExecutionRole.Arn
    Export:
      Name: CodePipelineExecutionRoleArn