AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Account Seed to be deployed new accounts in US-EAST-1

Resources:
  # ----------
  # IAM ROLES
  # ----------
  CodePipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipeline-Execution-Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  CloudFormationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormation-Deployment-Role
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service:
              - cloudformation.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # ----------
  # CODEPIPELINE - DevOps-CloudFormation
  # ----------
  DevOpsCloudFormationCodePipelineArtifactsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'devops-cloudformation-codepipeline-artifacts'

  # Create CodePipeline with 2 stages (Source, Build)
  DevOpsCloudFormationCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DevOps-Cloudformation-CodePipeline
      ArtifactStore:
        Type: S3
        Location: !Ref DevOpsCloudFormationCodePipelineArtifactsS3Bucket
      RestartExecutionOnUpdate: False
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Version: '1'
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: "arn:aws:codestar-connections:us-east-1:387310632530:connection/c6ff57ad-dab9-4ade-ac7d-ed4a5373c962"
                FullRepositoryId: "Travel-Project-2022/DevOps-Cloudformation"
                BranchName: "master"
                OutputArtifactFormat: "CODE_ZIP"
              RunOrder: 1
              OutputArtifacts:
                - Name: source-output-artifacts
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: source-output-artifacts
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Ref CloudFormationDeploymentRole.Arn
                StackName: DevOps-Cloudformation
                TemplatePath: 'source-output-artifacts::main.cfn.yaml'
              RunOrder: 1
              OutputArtifacts: [ ]

Outputs:
  CodePipelineExecutionRoleArn:
    Value: !GetAtt CodePipelineExecutionRole.Arn
    Export:
      Name: CodePipelineExecutionRoleArn